#!/usr/bin/env sh

SCRIPT_DIR=$(pwd)
XDG_CONFIG_HOME=~/.config

# Install Homebrew
if [ -z "$(command -v brew)" ]; then
    echo "--- Start installing Homebrew ---"

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ ! -d $XDG_CONFIG_HOME ]; then
    echo "$XDG_CONFIG_HOME directory does not exist"
    mkdir -p $XDG_CONFIG_HOME
fi

# gh
ln -fs $SCRIPT_DIR/gh $XDG_CONFIG_HOME
# git
ln -fs $SCRIPT_DIR/git $XDG_CONFIG_HOME
# zsh
ln -fs $SCRIPT_DIR/zsh $XDG_CONFIG_HOME
ln -fs $SCRIPT_DIR/zsh/.zshenv ~/.zshenv
