#!/usr/bin/env sh

SCRIPT_DIR=$(pwd)
XDG_CONFIG_HOME=~/.config

# Install Homebrew
if [ -z "$(command -v brew)" ]; then
    echo "--- Start installing Homebrew ---"

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ -z "$(command -v rustup)" ]; then
    echo "--- Start installing rustup ---"

    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi
