#!/bin/zsh
#
# This file, .zshrc, is sourced by zsh for each interactive shell session.
#
# Note: For historical reasons, there are other dotfiles, besides .zshenv and
# .zshrc, that zsh reads, but there is really no need to use those.

autoload -Uz compinit && compinit

##
# Homebrew
#
eval "$(/opt/homebrew/bin/brew shellenv)"

##
# Aqua settings
#

export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH"
export AQUA_GLOBAL_CONFIG=${AQUA_GLOBAL_CONFIG:-}:${XDG_CONFIG_HOME:-$HOME/.config}/aqua/aqua.yaml
export AQUA_POLICY_CONFIG=$HOME/.config/aqua/aqua-policy.yaml:$AQUA_POLICY_CONFIG

eval "$(starship init zsh)"

##
# Rust
#

if type cargo rustc &> /dev/null; then
  . "$HOME/.cargo/env"
fi

##
# Go settings
#

if type go &> /dev/null; then
  PATH="$(go env GOPATH)/bin:$PATH"
fi

##
# Sheldon
#

if type sheldon &> /dev/null; then
  export SHELDON_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/sheldon"
  eval "$(sheldon source)"
fi

##
# History settings
#
# Always set these first, so history is preserved, no matter what happens.
#

# Tell zsh where to store history.
HISTFILE=${XDG_DATA_HOME:=~/.local/share}/zsh/history

# Just in case: If the parent directory doesn't exist, create it.
# h removes a trailing pathname component, shortening the path by one directory level.
[[ -d $HISTFILE:h ]] || mkdir -p $HISTFILE:h

# Max number of entries to keep in history file.
SAVEHIST=$(( 100 * 1000 ))      # Use multiplication for readability.

# Max number of history entries to keep in memory.
HISTSIZE=$(( 1.2 * SAVEHIST ))  # Zsh recommended value

# Use modern file-locking mechanisms, for better safety & performance.
setopt HIST_FCNTL_LOCK

# Keep only the most recent copy of each duplicate entry in history.
setopt HIST_IGNORE_ALL_DUPS

# Auto-sync history between concurrent sessions.
setopt SHARE_HISTORY

##
# Kubernetes
#
if type kubectl &> /dev/null; then
  source <(kubectl completion zsh)
fi

if type krew &> /dev/null; then
  export PATH="${PATH}:${HOME}/.krew/bin"
fi
